version: '3.8'

services:
  jwt_auth_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jwt_auth_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - jwt_auth_network
    depends_on:
      jwt_auth_db:
        condition: service_healthy
      jwt_auth_redis:
        condition: service_started
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:WCGT2aimsa+ylGZaZ8xXOcJauLBh7mWSPReouAcRIyE=
      - DB_CONNECTION=mysql
      - DB_HOST=jwt_auth_db
      - DB_DATABASE=auth_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=jwt_auth_redis
      - REDIS_PORT=6379
    command: ["php-fpm"]

  jwt_auth_db:
    image: mysql:8.0
    container_name: jwt_auth_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./auth_db.sql:/docker-entrypoint-initdb.d/auth_db.sql
    networks:
      - jwt_auth_network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      start_period: 30s

  jwt_auth_redis:
    image: redis:alpine
    container_name: jwt_auth_redis
    restart: unless-stopped
    networks:
      - jwt_auth_network
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: jwt_auth_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jwt_auth_app
    networks:
      - jwt_auth_network

  node:
    image: node:18-alpine
    container_name: jwt_auth_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - jwt_auth_network
    command: ["tail", "-f", "/dev/null"]

networks:
  jwt_auth_network:

volumes:
  db_data:
